# name of CI workflow
name: CI   

# when to triger the workflow
on: push

# run a job, ther can be one or multiple jobs and they run paralley / sequentially
jobs:
    # mantion the name of the job
    linting:
        # make sure when the job will run
        runs-on: ${{ matrix.os }} # this will run the job on the OS mentioned in the matrix
        # this is the name of the job

        # using this to run the job on multiple OS
        # this is a matrix strategy, it will run the job on all the OS mentioned in the list
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: [3'.12', '3.11', '3.10'] # this will run the job on all the python versions mentioned in the list

        # steps to run the job
        steps:
            # need to defign the steps and then give them the name as well 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-versions }} # use the latest version of python

            - name: install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt    

            - name: run linting
              run: |
                    flake8 app.py